# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       otter-browser

# >> macros
# << macros

Summary:    Web browser
Version:    0.9.02
Release:    1
Group:      Applications/Internet
License:    GPLv3+
URL:        https://github.com/Emdek/otter
Source0:    %{name}-%{version}.tar.xz
Source100:  otter-browser.yaml
Patch0:     0001-Cast-to-qreal.patch
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5WebKit)
BuildRequires:  pkgconfig(Qt5WebKitWidgets)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  cmake
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
Web browser that aim to recreate the classic Opera UI using Qt 5.


%prep
%setup -q -n %{name}-%{version}/upstream

# 0001-Cast-to-qreal.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# Install desktop file
install -d %{buildroot}%{_datadir}/applications
install -p -m 0644 *.desktop %{buildroot}%{_datadir}/applications
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%doc CHANGELOG COPYING README.md
%{_bindir}/*
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/*/apps/otter-browser.png
%{_datadir}/otter-browser/locale/*.qm
# >> files
# << files
